#####################################################################################################################
#                                                                                                                   #
#                                                     EVENTS                                                        #
#                                                                                                                   #
#   message: The message to be displayed. Variables are inserted in the format <var:name>, such as <var:ipaddress>. #
#   regex: A regex expression paired with a string to find and replace parts of a message.                          #
#                                                                                                                   #
#####################################################################################################################

# Executed after variables have been inserted but before the message specific regex replacement on all messages
global_regex: ["Server":"Dat boi","players":"memes"]

round:
    onroundstart:
        # ipaddress
        message: "**Round started.**"
        regex: []
    onconnect:
        message: "Player attempting connection... (<var:ipaddress>)"
        regex: []
    ondisconnect:
        # ipaddress
        message: "A player has disconnected. (<var:ipaddress>)"
        regex: []
    oncheckroundend:
        message: "Checking if round has ended..."
        regex: []
    onroundend:
        # duration
        # dclassalive
        # dclassdead
        # dclassescaped
        # dclassstart
        # mtfalive
        # scientistsalive
        # scientistsdead
        # scientistsescaped
        # scientistsstart
        # scpalive
        # scpdead
        # scpkills
        # scpstart
        # warheaddetonated
        # zombies
        message: >+
            **Round ended after <var:duration> minutes.**
            ```
            Escaped D-class:    <var:dclassalive> / <var:dclassstart>
            Rescued Scientists: <var:scientistsalive> / <var:scientistsstart>
            Contained SCPs:     <var:scpdead> / <var:scpstart>
            Killed by SCP:      <var:scpkills>
            Warhead detonated:  <var:warheaddetonated>
            ```"
        regex: []
    onwaitingforplayers:
        message: "**Server is ready and waiting for players.**"
        regex: []
    onroundrestart:
        message: "**Round is restarting...**"
        regex: []
    onsetservername:
        message: "**Server name set to <var0>.**"
        regex: []

environment:
    onscp914activate:
        message: ""
        regex: []
    onstartcountdown:
        message: ""
        regex: []
    onstopcountdown:
        message: ""
        regex: []
    ondetonate:
        message: ""
        regex: []
    ondecontaminate:
        message: ""
        regex: []
    
player:
    onplayerdie:
        message: ""
        regex: []
    onplayerhurt:
        message: ""
        regex: []
    onplayerpickupitem:
        message: ""
        regex: []
    onplayerdropitem:
        message: ""
        regex: []
    onplayerjoin:
        message: ""
        regex: []
    onnicknameset:
        message: ""
        regex: []
    onassignteam:
        message: ""
        regex: []
    onsetrole:
        message: ""
        regex: []
    oncheckescape:
        message: ""
        regex: []
    onspawn:
        message: ""
        regex: []
    ondooraccess:
        message: ""
        regex: []
    onintercom:
        message: ""
        regex: []
    onintercomcooldowncheck:
        message: ""
        regex: []
    onpocketdimensionexit:
        message: ""
        regex: []
    onpocketdimensionenter:
        message: ""
        regex: []
    onpocketdimensiondie:
        message: ""
        regex: []
    onthrowgrenade:
        message: ""
        regex: []
    onplayerinfected:
        message: ""
        regex: []
    onspawnragdoll:
        message: ""
        regex: []
    onlure:
        message: ""
        regex: []
    oncontain106:
        message: ""
        regex: []

admin:
    onadminquery:
        message: ""
        regex: []
    onauthcheck:
        message: ""
        regex: []
    onban:
        message: ""
        regex: []
    
team:
    ondecideteamrespawnqueue:
        message: ""
        regex: []
    onsetrolemaxhp:
        message: ""
        regex: []
    onteamrespawn:
        message: ""
        regex: []
    onsetscpconfig:
        message: ""
        regex: []