#####################################################################################################################
#                                                                                                                   #
#                                                     EVENTS                                                        #
#                                                                                                                   #
#   message: The message to be displayed. Variables are inserted in the format <var:name>, such as <var:ipaddress>. #
#   regex: A regex expression paired with a string to find and replace parts of a message.                          #
#                                                                                                                   #
#####################################################################################################################

# Executed after variables have been inserted but before the message specific regex replacement on all messages
global_regex: ["::ffff:":""]

round:
    onroundstart:
        # ipaddress
        message: "**Round started.**"
        regex: []
    onconnect:
        message: "Player attempting connection... (<var:ipaddress>)"
        regex: []
    ondisconnect:
        # ipaddress
        message: "A player has disconnected. (<var:ipaddress>)"
        regex: []
    oncheckroundend:
        message: "Checking if round has ended..."
        regex: []
    onroundend:
        # duration
        # dclassalive
        # dclassdead
        # dclassescaped
        # dclassstart
        # mtfalive
        # scientistsalive
        # scientistsdead
        # scientistsescaped
        # scientistsstart
        # scpalive
        # scpdead
        # scpkills
        # scpstart
        # warheaddetonated
        # zombies
        message: >+
            **Round ended after <var:duration> minutes.**
            ```
            Escaped D-class:    <var:dclassalive> / <var:dclassstart>
            Rescued Scientists: <var:scientistsalive> / <var:scientistsstart>
            Contained SCPs:     <var:scpdead> / <var:scpstart>
            Killed by SCP:      <var:scpkills>
            Warhead detonated:  <var:warheaddetonated>
            ```"
        regex: []
    onwaitingforplayers:
        message: "**Server is ready and waiting for players.**"
        regex: []
    onroundrestart:
        message: "**Round is restarting...**"
        regex: []
    onsetservername:
        # servername
        message: "**Server name set to <var:servername>.**"
        regex: []

environment:
    onscp914activate:
        message: "SCP-914 has been activated on setting <var:knobsetting>."
        regex: []
    onstartcountdown:
        message: "**The on-site nuclear warhead has been activated.**"
        regex: []
    onstopcountdown:
        message: "**The on-site nuclear warhead has been deactivated.**"
        regex: []
    ondetonate:
        message: "**Detonation of the on-site nuclear warhead has been detected. Dispatching Foundation operatives to investigate.**"
        regex: []
    ondecontaminate:
        message: "**Light Containment Zone de-contamination has been initiated, all biological material will be destroyed.**"
        regex: []
    
player:
    onplayerdie:
        message: ""
        regex: []
    onplayerhurt:
        message: ""
        regex: []
    onplayerpickupitem:
        message: ""
        regex: []
    onplayerdropitem:
        message: ""
        regex: []
    onplayerjoin:
        message: ""
        regex: []
    onnicknameset:
        message: ""
        regex: []
    onassignteam:
        message: ""
        regex: []
    onsetrole:
        message: ""
        regex: []
    oncheckescape:
        message: ""
        regex: []
    onspawn:
        message: ""
        regex: []
    ondooraccess:
        message: ""
        regex: []
    onintercom:
        message: ""
        regex: []
    onintercomcooldowncheck:
        message: ""
        regex: []
    onpocketdimensionexit:
        message: ""
        regex: []
    onpocketdimensionenter:
        message: ""
        regex: []
    onpocketdimensiondie:
        message: ""
        regex: []
    onthrowgrenade:
        message: ""
        regex: []
    onplayerinfected:
        message: ""
        regex: []
    onspawnragdoll:
        message: ""
        regex: []
    onlure:
        message: ""
        regex: []
    oncontain106:
        message: ""
        regex: []

admin:
    onadminquery:
        # ipaddress
        # name 
        # playerid
        # steamid
        # class
        # handled
        # output
        # query
        # successful
        message: "Admin <var:name> (<var:steamid>) executed command '<var:query>'"
        regex: []
    onauthcheck:
        # allow 
        # authtype  
        # deniedmessage
        # ipaddress
        # name 
        # playerid 
        # steamid  
        # class    
        message: "<var:name> (<var:steamid>) checkaccess<var:allowed>."
        regex: ["checkaccesstrue":"was allowed access to the admin panel", "checkaccessfalse":"tried to get access to the admin panel but was denied"]
    onban:
        # allowban   
        # duration
        # reason
        # result
        # bannedipaddress
        # bannedname
        # bannedplayerid
        # bannedsteamid
        # bannedclass
        # adminipaddress
        # adminname
        # adminplayerid
        # adminsteamid
        # adminclass
        message: "Player <var:bannedname> (<var:bannedsteamid) was banned by <var:adminname> (<var:adminsteamid>) for <var:duration> minutes."
        regex: []
    
team:
    ondecideteamrespawnqueue:
        # teams
        message: "Respawn queue decided."
        regex: []
    onsetrolemaxhp:
        # players
        # spawnchaos
        message: "chaosspawn<var:spawnchaos>"
        regex: 
        [
            "chaosspawnfalse":"**MTF Epsilon-11 - \"Nine-Tailed Fox\" have arrived at the facility.**",
            "chaosspawntrue":"**Hostile incursion detected, intruders identified as members of hostile GOI \"Chaos Insurgency\".**"
        ]
    onteamrespawn:
        # maxhp
        # role
        message: "Max HP for <var:role> set to <var:maxhp>."
        regex: []
    onsetscpconfig:
        # banned049  
        # banned079  
        # banned096  
        # banned106  
        # banned173
        # banned939_53
        # banned939_89
        # 049amount
        # 079amount
        # 096amount
        # 106amount
        # 173amount
        # 939_53amount
        # 939_89amount
        message: "SCP settings set."
        regex: []